name: Build and Deploy 
on: 
  push:   
    branch: 
    - main

permission: 
  contents: read
  pages: write
  id-token: write
jobs: 
  runs-on: alpine-latest

  build:
    steps:
    - name: checkout main 
    uses: actions/checkout@v4
    - name: setup node
    uses: actions/setup-node@v4
     
  deploy:
    runs-on: alpine-latest
    steps:
    - name: Upload Pages artifact
    uses: actions/upload-pages-artifact@v2
    - name: deploy pages
    uses: actions/deploy-pages@v3
  
    
